program                 = { white_space, statement, white_space, "\n", white_space },
                        [ white_space, statement, white_space, [ "\n" ], white_space ] ;
    
white_space             = [ ? white space characters ? ] ;

statement               = assignment ;

assignment              = variable, "=", expression ;

variable                = ? letter ? ;

expression              = [ "(" ], 
                        ( number 
                        | variable 
                        | function_call 
                        | binary_operation 
                        | unary_operation ),
                        [ ")" ];

number                  = ? number ? ;

function_call           = function_name, "(", expression, ")" ;

binary_operation        = ( expression, binary_operator, expression ) 
                        | alt_mult_operation ;

alt_mult_operation      = expression, expression ;

unary_operation         = ( "|", expression, "|" ) 
                        | ( independent_expr, "!" );


independent_expr        = parenthesized_expr
                        | variable 
                        | function_call ;

parenthesized_expr      = "(", expression, ")" ;

function_name           = generic_function 
                        | logarithmic_function ;

generic_function        = ? generic_function_idenifier ? ;

logarithmic_function    =  "ln" 
                        | ( "log", [ number ] ) ;

binary_operator         = "=" 
                        | "+" 
                        | "-" 
                        | "*" 
                        | "/" 
                        | "^" 
                        | "mod" ;